"""empty message

Revision ID: 8fb76a08d0dd
Revises: 97eb333e036f
Create Date: 2023-01-21 00:24:59.406456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb76a08d0dd'
down_revision = '97eb333e036f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=140), nullable=True),
                    sa.Column('slug', sa.VARCHAR(length=140), nullable=True),
                    sa.Column('body', sa.TEXT(), nullable=True),
                    sa.Column('created', sa.DATETIME(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slug')
                    )
    # ### end Alembic commands ###
