"""empty message

Revision ID: 97eb333e036f
Revises: 94e3cc3d4363
Create Date: 2023-01-20 00:06:34.848986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97eb333e036f'
down_revision = '94e3cc3d4363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('title', sa.VARCHAR(length=140), nullable=True),
                    sa.Column('slug', sa.VARCHAR(length=140), nullable=True),
                    sa.Column('body', sa.TEXT(), nullable=True),
                    sa.Column('created', sa.DATETIME(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('slug')
                    )
    # ### end Alembic commands ###
